### ISSUE TITLE
"Incorrect string value" SQLException while inserting data with emoji(doesn't occur everytime)

### ISSUE THREAD

**Issue by colinchouzgl** [apache/shardingsphere#13023]
The exception occurred while inserting string value with emoji using ShardingSphere-Proxy. But sometimes it worked well.

```
[ERROR] 2021-10-13 19:23:08.131 [ShardingSphere-Command-18487] o.a.s.p.f.c.CommandExecutorTask - Exception occur:
java.sql.SQLException: Incorrect string value: '\xF0\x9F\xA5\x9B\xF0\x9F...' for column 'content' at row 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:127)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:790)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:808)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:103)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at org.apache.shardingsphere.proxy.backend.communication.jdbc.executor.callback.impl.ProxyStatementExecutorCallback.execute(ProxyStatementExecutorCallback.java:40)
	at org.apache.shardingsphere.proxy.backend.communication.jdbc.executor.callback.ProxyJDBCExecutorCallback.executeSQL(ProxyJDBCExecutorCallback.java:73)
	at org.apache.shardingsphere.proxy.backend.communication.jdbc.executor.callback.ProxyJDBCExecutorCallback.executeSQL(ProxyJDBCExecutorCallback.java:66)
	at org.apache.shardingsphere.proxy.backend.communication.jdbc.executor.callback.ProxyJDBCExecutorCallback.executeSQL(ProxyJDBCExecutorCallback.java:44)
	at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutorCallback.execute(JDBCExecutorCallback.java:85)
	at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutorCallback.execute(JDBCExecutorCallback.java:64)
	at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.syncExecute(ExecutorEngine.java:101)
	at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.parallelExecute(ExecutorEngine.java:97)
	at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.execute(ExecutorEngine.java:82)
	at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutor.execute(JDBCExecutor.java:65)
	at org.apache.shardingsphere.proxy.backend.communication.jdbc.executor.ProxyJDBCExecutor.execute(ProxyJDBCExecutor.java:71)
	at org.apache.shardingsphere.proxy.backend.communication.ProxySQLExecutor.useDriverToExecute(ProxySQLExecutor.java:184)
	at org.apache.shardingsphere.proxy.backend.communication.ProxySQLExecutor.execute(ProxySQLExecutor.java:137)
	at org.apache.shardingsphere.proxy.backend.communication.ProxySQLExecutor.execute(ProxySQLExecutor.java:126)
	at org.apache.shardingsphere.proxy.backend.communication.ProxyLockEngine.doExecute(ProxyLockEngine.java:103)
	at org.apache.shardingsphere.proxy.backend.communication.ProxyLockEngine.execute(ProxyLockEngine.java:81)
	at org.apache.shardingsphere.proxy.backend.communication.DatabaseCommunicationEngine.execute(DatabaseCommunicationEngine.java:126)
	at org.apache.shardingsphere.proxy.backend.text.data.impl.SchemaAssignedDatabaseBackendHandler.execute(SchemaAssignedDatabaseBackendHandler.java:55)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:57)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:99)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:72)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

SQL example:
```
INSERT INTO msg_chat_message_18 (content) VALUES ('欢迎牛奶🥛🥛🥛');
```
The charset of the db column is 'utf8mb4'

version: compiled from source code on master branch (commit bf812c0e85afa392c4013cb71fd2945f75189f81)

**Comment by RaigorJiang** [comment]
A user encountered a similar problem before, and his charset of the database is `utf8mb4` too. 
But then we found the root problem is that the character set of the `table` in this database is not `utf8mb4`, but `utf8`. 
So, I suggest you also check the character set of the table.

**Comment by colinchouzgl** [comment]
@TeslaCN

**Comment by RaigorJiang** [comment]
@colinchouzgl  OK.
Then, please provide your JDBC URL information (pay attention to confidentiality), including the JDBC URL information for the application to connect to the Proxy and the JDBC URL for the Proxy to connect to the physical database.

**Comment by RaigorJiang** [comment]
Please also check whether the JDBC parameters of `each` physical database connected by the Proxy are consistent.

In addition, you can try the following configuration (for each JDBC URL):
useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&character_set_server=utf8mb4&connectionCollation=utf8mb4_bin

**Comment by colinchouzgl** [comment]
Thx. I've tried the configuration you said several times and the exception has not occurred so far. I'll keep observing. :)

**Comment by RaigorJiang** [comment]
It seems that the problem has been resolved, I will close this issue.
 if the problem recurs, you can reopen it or submit a new issue.

**Comment by ashish19977** [comment]
@RaigorJiang, I have applied all the solutions mentioned above, but the problem still persists in my case. Sometimes it gives an error, and sometimes it works when I'm storing emojis. The issue gets resolved temporarily when I restart the proxy; after the restart, the error disappears for a while, but it reappears after some time. Once the error starts occurring, it continues to happen until I restart again.

Here is my JDBC URL:
`jdbc:mysql://127.0.0.1:3306/portal-uat-1?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&character_set_server=utf8mb4&connectionCollation=utf8mb4_bin`

`jdbc:mysql://127.0.0.1:3306/portal-uat21?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&character_set_server=utf8mb4&connectionCollation=utf8mb4_bin`

And here is my table schema:
CREATE TABLE `appt_data` (
  `id` int NOT NULL AUTO_INCREMENT,
  `appointment_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=28080676 DEFAULT CHARSET=utf8mb4;

This schema is same across both the datasouces.

**Comment by RaigorJiang** [comment]
> @RaigorJiang, I have applied all the solutions mentioned above, but the problem still persists in my case. Sometimes it gives an error, and sometimes it works when I'm storing emojis. The issue gets resolved temporarily when I restart the proxy; after the restart, the error disappears for a while, but it reappears after some time. Once the error starts occurring, it continues to happen until I restart again.
> 
> Here is my JDBC URL: `jdbc:mysql://127.0.0.1:3306/portal-uat-1?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&character_set_server=utf8mb4&connectionCollation=utf8mb4_bin`
> 
> `jdbc:mysql://127.0.0.1:3306/portal-uat21?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&character_set_server=utf8mb4&connectionCollation=utf8mb4_bin`
> 
> And here is my table schema: CREATE TABLE `appt_data` ( `id` int NOT NULL AUTO_INCREMENT, `appointment_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin, `created_at` datetime NOT NULL, PRIMARY KEY (`id`) ) ENGINE=InnoDB AUTO_INCREMENT=28080676 DEFAULT CHARSET=utf8mb4;
> 
> This schema is same across both the datasouces.

@ashish19977 Is characterEncoding specified in the URL that your application uses to connect to Proxy?

**Comment by ashish19977** [comment]
@RaigorJiang I'm using sequqlize to connect to proxy. I have also tried passing charset and collation options in sequqlize connection options, still issue remains same.
