### ISSUE TITLE
 when encrypt data is null, cause error

### ISSUE THREAD

**Issue by tianshuainan** [apache/shardingsphere#22230]
My version is ShardingSphere-JDBC 5.2.1, when requester_name is null, the error shows "could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement". Below is my configuration.
`
# dsr_request table
spring.shardingsphere.encrypt.tables.dsr_request.columns.requester_name.plainColumn=requester_name
spring.shardingsphere.encrypt.tables.dsr_request.columns.requester_name.cipherColumn=requester_name_cipher
spring.shardingsphere.encrypt.tables.dsr_request.columns.requester_name.encryptor=encryptor

spring.shardingsphere.encrypt.tables.dsr_request.columns.requester_email.plainColumn=requester_email
spring.shardingsphere.encrypt.tables.dsr_request.columns.requester_email.cipherColumn=requester_email_cipher
spring.shardingsphere.encrypt.tables.dsr_request.columns.requester_email.assistedQueryColumn=requester_email_assisted
spring.shardingsphere.encrypt.tables.dsr_request.columns.requester_email.encryptor=queryassistedencryptor
`
my customize encrypt is as below:
`
public class SdEncryptor implements Encryptor {
    private SdkEncryptService getSdkEncryptService() {
        return SpringContextUtils.getBean(SdkEncryptService.class);
    }

    @Override
    public String encrypt(Object o) {
        if (null == o) {
            return null;
        }
        String encryptData;
        try {
            encryptData = getSdkEncryptService().encryptData(String.valueOf(o));
        } catch (IOException e) {
            log.warn("SDK encrypt field {} failed", String.valueOf(o));
            throw new HulkException("SDK encrypt failed", e);
        }
        return encryptData;
    }

    @Override
    public Object decrypt(String s) {
        if (s == null) {
            return null;
        }
        String ret;
        try {
            ret = getSdkEncryptService().decryptData(s);
        } catch (IOException e) {
            log.warn("SDK decrypt cipher {} failed", s);
            throw new HulkException("SDK decrypt failed", e);
        }
        return ret;
    }

    @Override
    public String getType() {
       return "SdEncryptor";
    }

    @Override
    public Properties getProperties() {
        return null;
    }

    @Override
    public void setProperties(Properties properties) {}

    @Override
    public void init() {}
}

`

**Comment by strongduanmu** [comment]
Can you try master branch, we have already fixed this bug.

**Comment by tianshuainan** [comment]
When I asked last time, the assistedQueryColumn could not be null. This time, i don't use assistedQueryColumn, it still not support null value.

**Comment by tianshuainan** [comment]
such as :
spring.shardingsphere.encrypt.tables.dsr_request.columns.requester_name.plainColumn=requester_name
spring.shardingsphere.encrypt.tables.dsr_request.columns.requester_name.cipherColumn=requester_name_cipher
spring.shardingsphere.encrypt.tables.dsr_request.columns.requester_name.encryptor=encryptor

**Comment by strongduanmu** [comment]
Can you try master branch and give some feedback?

**Comment by strongduanmu** [comment]
We have optimized this exception in #21864 and #21686.

**Comment by strongduanmu** [comment]
I will close this issue since it has been fixed in master branch. If you have any problem when you test with master branch, you can submit a new issue.
