### ISSUE TITLE
When the Manager. alterRuleConfiguration (dataSourceName, configurations) method is used, the new schema is empty

### ISSUE THREAD

**Issue by liuzg459** [apache/shardingsphere#23839]
### Which version of ShardingSphere did you use?
V5.2.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC Standalone mode

### question
refer to [how to config actual-data-nodes while my actual-data-nodes tables is dynamic](https://github.com/apache/shardingsphere/issues/16725) 
When configuring a dynamic node, it cannot be routed normally. After debugging, I found that the new schema is empty

The code is as follow：
```
ContextManager contextManager = getContextManager(dataSource);
Collection<RuleConfiguration> configurations =contextManager.getMetaDataContexts().getMetaData().getDatabases().get(dataSourceName).getRuleMetaData().getConfigurations();
contextManager.alterRuleConfiguration(dataSourceName,configurations);
```

The calling method in ContextManager is as follows
```
public synchronized void alterRuleConfiguration(final String databaseName, final Collection<RuleConfiguration> ruleConfigs) {
try {
   Collection<ResourceHeldRule> staleResourceHeldRules = getStaleResourceHeldRules(databaseName);
   staleResourceHeldRules.forEach(ResourceHeldRule::closeStaleResource);
   metaDataContexts = createMetaDataContexts(databaseName, null, ruleConfigs);
metaDataContexts.getMetaData().getDatabases().putAll(newShardingSphereDatabase(metaDataContexts.getMetaData().getDatabase(databaseName)));
} catch (final SQLException ex) {
   log.error("Alter database: {} rule configurations failed", databaseName, ex);
}
}


private Map<String, ShardingSphereDatabase> newShardingSphereDatabase(final ShardingSphereDatabase originalDatabase) {
   Map<String, ShardingSphereDatabase> result = new LinkedHashMap<>(1, 1);
   result.put(originalDatabase.getName().toLowerCase(), new ShardingSphereDatabase(originalDatabase.getName(),
   originalDatabase.getProtocolType(), originalDatabase.getResourceMetaData(), originalDatabase.getRuleMetaData(),
   metaDataContexts.getPersistService().getDatabaseMetaDataService().loadSchemas(originalDatabase.getName())));
   return result;
}
```

The following code obtains null schema from H2 database
```
metaDataContexts.getPersistService().getDatabaseMetaDataService().loadSchemas(originalDatabase.getName())
```

It can operate normally after changing it to the following code

```
result.put(originalDatabase.getName().toLowerCase(), new ShardingSphereDatabase(originalDatabase.getName(),
originalDatabase.getProtocolType(), originalDatabase.getResource(), originalDatabase.getRuleMetaData(),
originalDatabase.getSchemas()));
```

Is there a problem with my configuration or with the framework itself?

**Comment by linghengqian** [comment]
- The context you've given is vague, can you provide a Git that includes unit tests for the assertions? Like https://github.com/linghengqian/shardingsphere-contextmanager-explore/blob/master/shardingsphere-v530-jdk8-modern/src/test/java/com/lingh/shardingspherev530jdk8modern/ContextManagerTests.java.

- Friendly reminder, there is a bug in DistSQL on ShardingSphere 5.2.0. Refer to https://github.com/apache/shardingsphere/issues/20952 .

**Comment by liuzg459** [comment]
我是参照 [https://github.com/apache/shardingsphere/issues/16725](https://github.com/apache/shardingsphere/issues/16725)的代码，执行`contextManager.alterRuleConfiguration(schemaName, newRuleConfigList);`后无法根据配置正常分页，

跟源码到：
`ContextManager.alterRuleConfiguration`和`newShardingSphereDatabase`方法，发现`newShardingSphereDatabase`方法的`loadSchema`会调用H2数据库查询之前的schema，并设置到新的schema，原始代码如下：
```
result.put(originalDatabase.getName().toLowerCase(), new ShardingSphereDatabase(originalDatabase.getName(),
originalDatabase.getProtocolType(), originalDatabase.getResource(), originalDatabase.getRuleMetaData(),
metaDataContexts.getPersistService().getDatabaseMetaDataService().load(originalDatabase.getName())));
```
`load`方法调用了H2数据库查询内存中的schema，但是并没有任何地方设置这个schema，所以是空的，将方法改成如下代码后，可正常调用（originalDatabase中保存的schema是正确的）
```
result.put(originalDatabase.getName().toLowerCase(), new ShardingSphereDatabase(originalDatabase.getName(),
originalDatabase.getProtocolType(), originalDatabase.getResource(), originalDatabase.getRuleMetaData(),
originalDatabase.getSchemas()));
```

**Comment by linghengqian** [comment]
- Looks like it was fixed by https://github.com/apache/shardingsphere/pull/21037.

**Comment by zhaojinchao95** [comment]
@liuzg459 Can you upgrade version and try it again?

**Comment by liuzg459** [comment]
I upgrade version to V5.2.1, But still not work when use sql 
```
select count 1 from table_1 union all select count 1 from table_2
```
It works  with 
```
select * from table_1 union all select * from table_2
```

Same problems as the previous version V5.2.0

**Comment by linghengqian** [comment]
- I can't understand why one SQL is ok and the other is not. Do you have unit tests for easy debugging?

**Comment by liuzg459** [comment]
我做了个demo程序 [demo](https://gitee.com/jasonliu459/sharding-jdbc5.2.1actualnode),
重写了`ContextManager`类，441行，您执行`ShardingJdbcActualnodeApplicationTests.test`方法，分别注释`ContextManager`的441和444行能得到不同的运行结果，还请麻烦帮忙看下是我配置有问题还是框架的问题

**Comment by linghengqian** [comment]
- I tried it a while ago, but the CDN used by Gitee's static resources blocks access from some countries.  At least in Spain, my friend and I can't log into Gitee normally.

**Comment by liuzg459** [comment]
Please try [https://github.com/liuzg459/sharding-jdbc5.2.1actualnode2.git](https://github.com/liuzg459/sharding-jdbc5.2.1actualnode2.git),Thanks a lot!

**Comment by linghengqian** [comment]
- You don't seem to be persisting metadata to the "memory space" where the metadata really should be. Although the versions are different, the ContextManager class you modified does not seem to do the same `clearServiceCache()` operation as in StandaloneModeContextManager. Even if you don't know `clearServiceCache()`, you can force a refresh of all metadata. Refer to https://github.com/apache/shardingsphere/blob/5.3.1/mode/type/standalone/core/src/main/java/org/apache/shardingsphere/mode/manager/standalone/StandaloneModeContextManager.java and https://github.com/apache/shardingsphere/blob/5.3.1/mode/core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java#L465 .

- Since you did not actually use H2Database to write unit tests, and did not give the corresponding SQL file, it is a bit difficult for me to see the design source of this ContextManager.
