### ISSUE TITLE
Content error in SHARDINGSPHERE-JDBC Quick start doc

### ISSUE THREAD

**Issue by CoderMayhem** [apache/shardingsphere#23939]
## Bug Report

In the SHARDINGSPHERE-JDBC quickstart document ([link](https://github.com/apache/shardingsphere/blob/master/docs/document/content/quick-start/shardingsphere-jdbc-quick-start.en.md)) it says there are four ways to configure Apache Sharding sphere but it mentions only two, Java and YAML.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
Latest

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
JDBC docs

### Expected behavior
Either mention 2 ways to configure or add more methods other than JAVA and YAML.

### Actual behavior
![Screenshot 2023-02-02 15:57:18](https://user-images.githubusercontent.com/56952811/216299891-f8927303-c2a0-438c-99cd-70fdc5a30135.png)

### Reason analyze (If you can)
Typing error

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Check out : [link](https://shardingsphere.apache.org/document/current/en/quick-start/shardingsphere-jdbc-quick-start/)

**Comment by Pace2Car** [comment]
This has been corrected in #23818

**Comment by RaigorJiang** [comment]
@Pace2Car Yes, the issue still exists

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/5668787/216767725-1b2e3f5d-a160-4048-bab0-7b16046979e8.png">

Hi @CoderMayhem, Would you like to submit a PR to fix it?

**Comment by CoderMayhem** [comment]
Yes, I'll open a PR. Thanks.

**Comment by Pace2Car** [comment]
@CoderMayhem Thank you!
