### ISSUE TITLE
org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager#createConnections leaks connection if replay throws exception

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [apache/shardingsphere#34418]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

`org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager#createConnections(java.lang.String, java.lang.String, javax.sql.DataSource, int, org.apache.shardingsphere.infra.executor.sql.execute.engine.ConnectionMode)`  leaks connection if replay throws exception.

Thread stack:
```
java.sql.SQLNonTransientConnectionException: (conn=2848) Socket error
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:300)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:366)
	at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:938)
	at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:854)
	at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:773)
	at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:697)
	at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:553)
	at org.mariadb.jdbc.Connection.setAutoCommit(Connection.java:204)
	at com.alibaba.druid.filter.FilterChainImpl.connection_setAutoCommit(FilterChainImpl.java:699)
	at com.alibaba.druid.filter.FilterAdapter.connection_setAutoCommit(FilterAdapter.java:964)
	at com.alibaba.druid.filter.FilterChainImpl.connection_setAutoCommit(FilterChainImpl.java:694)
	at com.alibaba.druid.filter.logging.LogFilter.connection_setAutoCommit(LogFilter.java:467)
	at com.alibaba.druid.filter.FilterChainImpl.connection_setAutoCommit(FilterChainImpl.java:694)
	at com.alibaba.druid.filter.FilterAdapter.connection_setAutoCommit(FilterAdapter.java:964)
	at com.alibaba.druid.filter.FilterChainImpl.connection_setAutoCommit(FilterChainImpl.java:694)
	at com.alibaba.druid.filter.FilterAdapter.connection_setAutoCommit(FilterAdapter.java:964)
	at com.alibaba.druid.filter.FilterChainImpl.connection_setAutoCommit(FilterChainImpl.java:694)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.setAutoCommit(ConnectionProxyImpl.java:416)
	at com.alibaba.druid.pool.DruidPooledConnection.setAutoCommit(DruidPooledConnection.java:732)
	at org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager.lambda$setAutoCommit$0(DriverDatabaseConnectionManager.java:165)
	at org.apache.shardingsphere.driver.jdbc.adapter.invocation.MethodInvocationRecorder.replay(MethodInvocationRecorder.java:53)
	at org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager.createConnections(DriverDatabaseConnectionManager.java:386)
	at org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager.getConnections(DriverDatabaseConnectionManager.java:359)
	at org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager.getRandomConnection(DriverDatabaseConnectionManager.java:335)
	at xxx.ShardingDBConfiguration$SmartConnection.prepareStatement(ShardingDBConfiguration.java:50)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:88)
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:90)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:60)
	at org.apache.ibatis.executor.BatchExecutor.doUpdate(BatchExecutor.java:71)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at jdk.internal.reflect.GeneratedMethodAccessor168.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at xxx.MysqlInterceptor.intercept(MysqlInterceptor.java:58)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:59)
	at jdk.proxy2/jdk.proxy2.$Proxy273.update(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor168.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at jdk.proxy2/jdk.proxy2.$Proxy273.update(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	... 44 more
Caused by: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.read(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(Unknown Source)
	at java.base/java.net.Socket$SocketInputStream.read(Unknown Source)
	at java.base/java.io.BufferedInputStream.fill(Unknown Source)
	at java.base/java.io.BufferedInputStream.read1(Unknown Source)
	at java.base/java.io.BufferedInputStream.read(Unknown Source)
	at org.mariadb.jdbc.client.socket.impl.PacketReader.readReusablePacket(PacketReader.java:62)
	at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:153)
	at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:915)
	... 85 more
```

### Which version of ShardingSphere did you use?
5.5.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
Connection is closed even some exception throwed during replay.

### Actual behavior

Connection is never closed when some exception throwed during replay.

### Reason analyze (If you can)

`org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager#createConnections(java.lang.String, java.lang.String, javax.sql.DataSource, int, org.apache.shardingsphere.infra.executor.sql.execute.engine.ConnectionMode)`  didn't handle exception while calling `replay` method.

**Comment by linghengqian** [comment]
- Will this be fixed by https://github.com/apache/shardingsphere/pull/34463 ? However, the master branch actually does not have nativeTest for the mariadb jdbc driver under the GraalVM Native Image. The current issue looks a bit like a need for more information to me.

**Comment by Nick-The-Uncharted** [comment]
@terrymanu @linghengqian Sorry for being too busy to reply,  I am unable to push code to github due to the security policy of my company. I believe #34463 didn't fix this issue because it didn't change code of  
`org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager.createConnections(DriverDatabaseConnectionManager.java:386)`

**Comment by linghengqian** [comment]
@Nick-The-Uncharted Can you share a git with minimal reproducible unit tests? I'm surprised that the handling of #34463 didn't fix this issue.

**Comment by linghengqian** [comment]
- So what you are talking about is `private List<Connection> createConnections(final String databaseName, final String dataSourceName, final DataSource dataSource, final int connectionSize, final TransactionConnectionContext transactionConnectionContext) throws SQLException` instead of `private List<Connection> createConnections(final String databaseName, final String dataSourceName, final DataSource dataSource, final int connectionSize, final ConnectionMode connectionMode) throws SQLException`?

**Comment by Nick-The-Uncharted** [comment]
@linghengqian Sorry for misreading the code, the change in #34463 do fixed my problem, but `methodInvocationRecorder.replay(connection);` in  `createConnections(final String databaseName, final String dataSourceName, final DataSource dataSource, final int connectionSize,
                                               final TransactionConnectionContext transactionConnectionContext)` do still have a chance of leaking connection if relay throws.

**Comment by linghengqian** [comment]
- @Nick-The-Uncharted The interesting thing here is that I can actually only reproduce the connection leak bug mentioned in #34463 . I need someone to show me how to make the connection leak happen in another method, because it seems that there is a higher-level method that handles the exception.

**Comment by linghengqian** [comment]
- Just in case someone doesn't know `try-catch` is java syntax. It's hard to tell what there is to do here.
```java
private List<Connection> createConnections(final String databaseName, final String dataSourceName, final DataSource dataSource, final int connectionSize,
                                               final TransactionConnectionContext transactionConnectionContext) throws SQLException {
        List<Connection> result = new ArrayList<>(connectionSize);
        for (int i = 0; i < connectionSize; i++) {
            try {
                Connection connection = createConnection(databaseName, dataSourceName, dataSource, transactionConnectionContext);
                result.add(connection);
            } catch (final SQLException ex) {
                for (Connection each : result) {
                    each.close();
                }
                throw new OverallConnectionNotEnoughException(connectionSize, result.size(), ex).toSQLException();
            }
        }
        return result;
    }
```

**Comment by linghengqian** [comment]
- My understanding is that to trigger the judgment condition of `org.apache.shardingsphere.infra.executor.sql.execute.engine.ConnectionMode.CONNECTION_STRICTLY`, the value of `maxConnectionsSizePerQuery` of `org.apache.shardingsphere.infra.executor.sql.prepare.AbstractExecutionPrepareEngine` needs to be less than the total number of `org.apache.shardingsphere.infra.executor.sql.context.SQLUnit`. And `maxConnectionsSizePerQuery` is obtained from `max-connections-size-per-query` in the configuration file, and the default value is `1`.

- Building such a unit test requires some interesting hacking of HikariCP. And this can only be reproduced with the help of the connection leak bug of seata client 2.2.0.
```yaml
dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    jdbcUrl: jdbc:tc:postgresql:17.2-bookworm://test-native-transactions-base/demo_ds_0?TC_INITSCRIPT=test-native/sql/seata-script-client-at-postgresql.sql
    maximumPoolSize: 1
  ds_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    jdbcUrl: jdbc:tc:postgresql:17.2-bookworm://test-native-transactions-base/demo_ds_1?TC_INITSCRIPT=test-native/sql/seata-script-client-at-postgresql.sql
    maximumPoolSize: 1
  ds_2:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    jdbcUrl: jdbc:tc:postgresql:17.2-bookworm://test-native-transactions-base/demo_ds_2?TC_INITSCRIPT=test-native/sql/seata-script-client-at-postgresql.sql
    maximumPoolSize: 1
```
```shell
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 68.62 s <<< FAILURE! -- in org.apache.shardingsphere.test.natived.jdbc.transactions.base.SeataTest
[ERROR] org.apache.shardingsphere.test.natived.jdbc.transactions.base.SeataTest.assertShardingInSeataTransactions -- Time elapsed: 68.60 s <<< ERROR!
java.sql.SQLException: 

More details: java.sql.SQLTransientConnectionException: HikariPool-58 - Connection is not available, request timed out after 30001ms.
        at org.apache.shardingsphere.infra.exception.core.external.sql.ShardingSphereSQLException.toSQLException(ShardingSphereSQLException.java:81)
        at org.apache.shardingsphere.infra.exception.dialect.SQLExceptionTransformEngine.toSQLException(SQLExceptionTransformEngine.java:54)
        at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.executeUpdate(ShardingSphereStatement.java:138)
        at com.zaxxer.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:119)
        at com.zaxxer.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java)
        at org.apache.shardingsphere.test.natived.commons.repository.OrderRepository.createTableIfNotExistsInPostgres(OrderRepository.java:76)
        at org.apache.shardingsphere.test.natived.jdbc.transactions.base.SeataTest.initEnvironment(SeataTest.java:102)
        at org.apache.shardingsphere.test.natived.jdbc.transactions.base.SeataTest.assertShardingInSeataTransactions(SeataTest.java:96)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
Caused by: java.sql.SQLTransientConnectionException: HikariPool-58 - Connection is not available, request timed out after 30001ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
        at org.apache.shardingsphere.infra.database.core.metadata.database.datatype.DataTypeRegistry.load(DataTypeRegistry.java:53)
        at org.apache.shardingsphere.infra.database.core.metadata.data.loader.MetaDataLoader.load(MetaDataLoader.java:65)
        at org.apache.shardingsphere.infra.metadata.database.schema.builder.GenericSchemaBuilder.loadSchemas(GenericSchemaBuilder.java:90)
        at org.apache.shardingsphere.infra.metadata.database.schema.builder.GenericSchemaBuilder.build(GenericSchemaBuilder.java:73)
        at org.apache.shardingsphere.mode.metadata.refresher.metadata.pushdown.type.table.CreateTablePushDownMetaDataRefresher.refresh(CreateTablePushDownMetaDataRefresher.java:57)
        at org.apache.shardingsphere.mode.metadata.refresher.metadata.pushdown.type.table.CreateTablePushDownMetaDataRefresher.refresh(CreateTablePushDownMetaDataRefresher.java:45)
        at org.apache.shardingsphere.mode.metadata.refresher.metadata.pushdown.PushDownMetaDataRefreshEngine.refresh(PushDownMetaDataRefreshEngine.java:79)
        at org.apache.shardingsphere.driver.executor.engine.pushdown.jdbc.DriverJDBCPushDownExecuteUpdateExecutor.doExecuteUpdate(DriverJDBCPushDownExecuteUpdateExecutor.java:117)
        at org.apache.shardingsphere.driver.executor.engine.pushdown.jdbc.DriverJDBCPushDownExecuteUpdateExecutor.lambda$executeUpdate$0(DriverJDBCPushDownExecuteUpdateExecutor.java:93)
        at org.apache.shardingsphere.driver.executor.engine.transaction.DriverTransactionalExecutor.execute(DriverTransactionalExecutor.java:56)
        at org.apache.shardingsphere.driver.executor.engine.pushdown.jdbc.DriverJDBCPushDownExecuteUpdateExecutor.executeUpdate(DriverJDBCPushDownExecuteUpdateExecutor.java:92)
        at org.apache.shardingsphere.driver.executor.engine.DriverExecuteUpdateExecutor.executeUpdate(DriverExecuteUpdateExecutor.java:80)
        at org.apache.shardingsphere.driver.executor.engine.facade.DriverExecutorFacade.executeUpdate(DriverExecutorFacade.java:126)
        at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.executeUpdate(ShardingSphereStatement.java:189)
        at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement.executeUpdate(ShardingSphereStatement.java:133)
        ... 8 more
```

**Comment by linghengqian** [comment]
- From my point of view it is expected behavior for `CONNECTION_STRICTLY` connection mode. The unit test correctly asserts this error.
```shell
Error:  org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManagerTest.assertGetConnectionsWhenConnectionCreateFailed -- Time elapsed: 0.008 s <<< FAILURE!
java.lang.AssertionError: 

Expected: is "Can not get 3 connections one time, partition succeed connection(0) have released. Please consider increasing the 'maxPoolSize' of the data sources or decreasing the 'max-connections-size-per-query' in properties.\nMore details: java.sql.SQLException: Mock invalid data source"
     but: was "Mock invalid data source"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManagerTest.assertGetConnectionsWhenConnectionCreateFailed(DriverDatabaseConnectionManagerTest.java:161)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
```

**Comment by linghengqian** [comment]
Closed because the current issue is meaningless.
