### ISSUE TITLE
Failed to switch schema, please terminate current transaction.

### ISSUE THREAD

**Issue by hongfuli** [apache/shardingsphere#5531]
### Which version of ShardingSphere did you use?
4.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy
### Steps to reproduce the behavior

My project developed by `Django` wants to connect mysql proxy,  errors are always reported when initializing the connection, but after the initialization is complete, it can continue to work fine.

I used wireshark to grab the data package that initialized the connection process(the login process is omitted):
```
SET AUTOCOMMIT = 0
SELECT @@SQL_AUTO_IS_NULL
SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED

get error response: 2Unknown exception: [Failed to switch schema, please terminate current transaction.]
```

the content of `config-sharding.yaml`:
```yaml
schemaName: sharding_db

dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false
    username: root
    password: admin
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_1:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false
    username: root
    password: admin
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50

shardingRule:
  tables:
    t_order:
      actualDataNodes: ds_${0..1}.t_order_${0..1}
      tableStrategy:
        inline:
          shardingColumn: order_id
          algorithmExpression: t_order_${order_id % 2}
      keyGenerator:
        type: SNOWFLAKE
        column: order_id
    t_order_item:
      actualDataNodes: ds_${0..1}.t_order_item_${0..1}
      tableStrategy:
        inline:
          shardingColumn: order_id
          algorithmExpression: t_order_item_${order_id % 2}
      keyGenerator:
        type: SNOWFLAKE
        column: order_item_id
  bindingTables:
    - t_order,t_order_item
  defaultDatabaseStrategy:
    inline:
      shardingColumn: user_id
      algorithmExpression: ds_${user_id % 2}
  defaultTableStrategy:
    none:
```

**Comment by kimmking** [comment]
what is the whole error logs in proxy console?

**Comment by cherrylzhao** [comment]
thanks for feedback, I can do some investigate for that.

**Comment by hongfuli** [comment]
> console

[ERROR] 17:02:22.479 [ShardingSphere-Command-3] o.a.s.s.b.c.j.c.BackendConnection - Cannot do switch, exceed maximum retry count:[5].
[ERROR] 17:02:22.479 [ShardingSphere-Command-3] o.a.s.s.f.c.CommandExecutorTask - Exception occur:
org.apache.shardingsphere.underlying.common.exception.ShardingSphereException: Failed to switch schema, please terminate current transaction.
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.setCurrentSchema(BackendConnection.java:112)
        at org.apache.shardingsphere.shardingproxy.backend.text.admin.BroadcastBackendHandler.execute(BroadcastBackendHandler.java:50)
        at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:73)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:93)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by hongfuli** [comment]
> what is the whole error logs in proxy console?

[ERROR] 17:02:22.479 [ShardingSphere-Command-3] o.a.s.s.b.c.j.c.BackendConnection - Cannot do switch, exceed maximum retry count:[5].
[ERROR] 17:02:22.479 [ShardingSphere-Command-3] o.a.s.s.f.c.CommandExecutorTask - Exception occur:
org.apache.shardingsphere.underlying.common.exception.ShardingSphereException: Failed to switch schema, please terminate current transaction.
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.setCurrentSchema(BackendConnection.java:112)
        at org.apache.shardingsphere.shardingproxy.backend.text.admin.BroadcastBackendHandler.execute(BroadcastBackendHandler.java:50)
        at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:73)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:93)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by ssxlulu** [comment]
I think sharding-proxy doesn't support the sql syntax `SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED` which ORM framework send.

**Comment by hongfuli** [comment]
According to my guess, i think that `sharding-proxy` did not handle the mysql protocol correctly.

The seq 11:  SET AUTOCOMMIT = 0

<img width="1291" alt="sharding-proxy_pcapng" src="https://user-images.githubusercontent.com/837054/81567661-cec44b80-93c6-11ea-92c4-6ad7359ef521.png">

but the response of server status is incorrect(the seq 13).
If the correct server status is returned here, the client will call `SET AUTOCOMMIT = 1` next, and eventually all become normal.

<img width="1314" alt="sharding-proxy_pcapng" src="https://user-images.githubusercontent.com/837054/81567768-ffa48080-93c6-11ea-8d97-87a0affc3828.png">

**Comment by cherrylzhao** [comment]
what's the JDBC-driver are you using? from my understand it's very strange sending a 'SET AUTOCOMMIT =1 ' command after 'SET AUTOCOMMIT=0`

**Comment by cherrylzhao** [comment]
similar with #3546, I have some ideas to enhance it recently.

**Comment by hongfuli** [comment]
> what's the JDBC-driver are you using? from my understand it's very strange sending a `SET AUTOCOMMIT =1` command after `SET AUTOCOMMIT=0`

the JDBC-driver is `mysql-connector-java-5.1.47.jar`,
but i think this problem has nothing to do with it,  it's related to `django` initinalization.

**Comment by cherrylzhao** [comment]
agree with it, I will do something to be compatible with it.

**Comment by hongfuli** [comment]
i  updated my previous comment

> The root reason of this problem is that proxy cannot return the correct server satus for `set autocommit = 1 | 0`. If the client ignores this return, there is no problem. Once the client cares about this state, it will cause client problems

**Comment by cherrylzhao** [comment]
yes, there are two problems exist in your issue.
  1. status flag of MySQLOKPacket is wrong, see [OKPacket](https://dev.mysql.com/doc/internals/en/packet-OK_Packet.html) of MySQL
  2. transaction across schema could not be supported in BackendConnection

**Comment by hongfuli** [comment]
Will the issue be resolved in the 5 milestone or 4.1.x version? I hope to solve it as soon as possible because I need it urgently :)

**Comment by cherrylzhao** [comment]
it should be enhanced in 5.x, we have not 4.1.x release plan recently.

**Comment by cherrylzhao** [comment]
@hongfuli can you push your Django project to github, I want to verify the test result

**Comment by hongfuli** [comment]
@cherrylzhao 
https://github.com/hongfuli/sharding-proxy-django/

**Comment by cherrylzhao** [comment]
@hongfuli this example could not run on my pc, please try to test using my branch code:
git clone -b issue#5531-test https://github.com/cherrylzhao/incubator-shardingsphere.git

**Comment by hongfuli** [comment]
> git clone -b issue#5531-test https://github.com/cherrylzhao/incubator-shardingsphere.git
build failed :(

```
[INFO] Running org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutorTest
[ERROR] Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.005 s <<< FAILURE! - in org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutorTest
[ERROR] assertIsErrorResponse(org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutorTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NullPointerException
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutorTest.<init>(MySQLComQueryPacketExecutorTest.java:50)

[ERROR] assertIsQuery(org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutorTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NullPointerException
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutorTest.<init>(MySQLComQueryPacketExecutorTest.java:50)

[ERROR] assertIsUpdateResponse(org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutorTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NullPointerException
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutorTest.<init>(MySQLComQueryPacketExecutorTest.java:50)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   MySQLCommandExecutorFactoryTest.assertNewInstance:59 » NullPointer
[ERROR]   MySQLComStmtExecuteExecutorTest.assertIsErrorResponse:59 » NullPointer
[ERROR]   MySQLComStmtExecuteExecutorTest.assertIsQuery:88 » NullPointer
[ERROR]   MySQLComStmtExecuteExecutorTest.assertIsUpdateResponse:74 » NullPointer
[ERROR]   MySQLComQueryPacketExecutorTest.<init>:50 » NullPointer
[ERROR]   MySQLComQueryPacketExecutorTest.<init>:50 » NullPointer
[ERROR]   MySQLComQueryPacketExecutorTest.<init>:50 » NullPointer
[INFO]
[ERROR] Tests run: 33, Failures: 0, Errors: 7, Skipped: 0
```

**Comment by cherrylzhao** [comment]
I have fixed the unit test error, you can pull it again or just -DskipTests

**Comment by hongfuli** [comment]
i can't startup the `sharding-proxy` compiled with your branch, and i used the same `conf-sharding.yaml`, the errors:
```java
Exception in thread "main" Cannot create property=shardingRule for JavaBean=org.apache.shardingsphere.shardingproxy.config.yaml.YamlProxyRuleConfiguration@3ac3fd8b
 in 'reader', line 1, column 1:
    schemaName: sharding_db
    ^
Cannot create property=tables for JavaBean=org.apache.shardingsphere.core.yaml.config.sharding.YamlShardingRuleConfiguration@43a25848
 in 'reader', line 22, column 3:
      tables:
      ^
Cannot create property=tableStrategy for JavaBean=org.apache.shardingsphere.core.yaml.config.sharding.YamlTableRuleConfiguration@2133c8f8
 in 'reader', line 24, column 7:
          actualDataNodes: ds_${0..1}.t_or ...
          ^
Cannot create property=inline for JavaBean=org.apache.shardingsphere.core.yaml.config.sharding.YamlShardingStrategyConfiguration@49e4cb85
 in 'reader', line 26, column 9:
            inline:
            ^
Unable to find property 'inline' on class: org.apache.shardingsphere.core.yaml.config.sharding.YamlShardingStrategyConfiguration
 in 'reader', line 27, column 11:
              shardingColumn: order_id
              ^

 in 'reader', line 26, column 9:
            inline:
            ^

 in 'reader', line 23, column 5:
        t_order:
        ^

 in 'reader', line 22, column 3:
      tables:
      ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:312)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:345)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:410)
	at org.apache.shardingsphere.underlying.common.yaml.engine.YamlEngine.unmarshal(YamlEngine.java:74)
	at org.apache.shardingsphere.shardingproxy.config.ShardingConfigurationLoader.loadRuleConfiguration(ShardingConfigurationLoader.java:79)
	at org.apache.shardingsphere.shardingproxy.config.ShardingConfigurationLoader.load(ShardingConfigurationLoader.java:60)
	at org.apache.shardingsphere.shardingproxy.Bootstrap.main(Bootstrap.java:80)
Caused by: Cannot create property=tables for JavaBean=org.apache.shardingsphere.core.yaml.config.sharding.YamlShardingRuleConfiguration@43a25848
 in 'reader', line 22, column 3:
      tables:
      ^
Cannot create property=tableStrategy for JavaBean=org.apache.shardingsphere.core.yaml.config.sharding.YamlTableRuleConfiguration@2133c8f8
 in 'reader', line 24, column 7:
          actualDataNodes: ds_${0..1}.t_or ...
          ^
Cannot create property=inline for JavaBean=org.apache.shardingsphere.core.yaml.config.sharding.YamlShardingStrategyConfiguration@49e4cb85
 in 'reader', line 26, column 9:
            inline:
            ^
Unable to find property 'inline' on class: org.apache.shardingsphere.core.yaml.config.sharding.YamlShardingStrategyConfiguration
 in 'reader', line 27, column 11:
              shardingColumn: order_id
              ^

 in 'reader', line 26, column 9:
            inline:
            ^

 in 'reader', line 23, column 5:
        t_order:
        ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:312)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:297)
	... 11 more
Caused by: Cannot create property=tableStrategy for JavaBean=org.apache.shardingsphere.core.yaml.config.sharding.YamlTableRuleConfiguration@2133c8f8
 in 'reader', line 24, column 7:
          actualDataNodes: ds_${0..1}.t_or ...
          ^
Cannot create property=inline for JavaBean=org.apache.shardingsphere.core.yaml.config.sharding.YamlShardingStrategyConfiguration@49e4cb85
 in 'reader', line 26, column 9:
            inline:
            ^
Unable to find property 'inline' on class: org.apache.shardingsphere.core.yaml.config.sharding.YamlShardingStrategyConfiguration
 in 'reader', line 27, column 11:
              shardingColumn: order_id
              ^

 in 'reader', line 26, column 9:
            inline:
            ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:312)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:373)
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:147)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:354)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:170)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:297)
	... 14 more
Caused by: Cannot create property=inline for JavaBean=org.apache.shardingsphere.core.yaml.config.sharding.YamlShardingStrategyConfiguration@49e4cb85
 in 'reader', line 26, column 9:
            inline:
            ^
Unable to find property 'inline' on class: org.apache.shardingsphere.core.yaml.config.sharding.YamlShardingStrategyConfiguration
 in 'reader', line 27, column 11:
              shardingColumn: order_id
              ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:312)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:297)
	... 22 more
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'inline' on class: org.apache.shardingsphere.core.yaml.config.sharding.YamlShardingStrategyConfiguration
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:132)
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:121)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.getProperty(Constructor.java:322)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:240)
	... 25 more
```

**Comment by hongfuli** [comment]
I still have the same problem.

Actually you don't need Django to verify, just need to check the `status flag` after sending the request`SET AUTOCOMMIT = 0`.

**Comment by cherrylzhao** [comment]
yes I know, but it's very difficult to implement  `SERVER_SESSION_STATE_CHANGED` protocol in current architecture, so I want to test a alternate way

**Comment by hongfuli** [comment]
@cherrylzhao 
Can I use a fixed version for this problem?

**Comment by ChuckPerry** [comment]
did this problem resoled? I catch same problem in qrtz frame.

**Comment by lijintaotzx** [comment]
Has the problem been solved ? I have the same problem in my django project.

**Comment by 1006572352** [comment]
The same error info in sqoop1.4.6+sharding-proxy-5.0.0-RC1

**Comment by nimeijian** [comment]
When I use dataX to connect shardingproxy, I encountered the same error. I tried version 3.1.0/4.1.1/5.0.0-alpha, all have this problem.

**Comment by yoloz** [comment]
use dbcp2 and connection.setAutoCommit(false), get the same error, mysqlProxy version 5.0-alpha

**Comment by yoloz** [comment]
```java
package org.apache.shardingsphere.proxy.backend.communication.jdbc.connection;
public final class BackendConnection implements JDBCExecutionConnection {
 /**
     * Change schema of current channel.
     *
     * @param schemaName schema name
     */
   public void setCurrentSchema(final String schemaName) {
        //todo 临时处理
        if (!Strings.isNullOrEmpty(this.schemaName) && this.schemaName.equals(schemaName)) return;
        if (transactionStatus.isInTransaction()) {
            throw new ShardingSphereException("Failed to switch schema, please terminate current transaction.");
        }
        this.schemaName = schemaName;
    }
}
```
as the same schema can  directly return ?
@cherrylzhao

**Comment by huangtaogege** [comment]
> 当我使用dataX连接分片代理时，我遇到了同样的错误。我试过3.1.0/4.1.1/5.0.0-alpha版本，都存在这个问题。

 有解决么

**Comment by userkdg** [comment]
+1 都到2021年尾了，bug还在？

**Comment by anxinlong** [comment]
+1 this issue has been open for more than one year😂

**Comment by jingshanglu** [comment]
It maybe fixed by #14983 .
